---
services:
  umatigateway:
    image: ghcr.io/umati/umatigateway:develop
    container_name: umatigateway
    volumes:
      - ./umatiGatewayConfig.xml:/app/umatiGatewayConfig.xml
    depends_on:
      - sampleserver
    ports:
      - 8080:8080  # HostPort:ContainerPort

  sampleserver:
    image: ghcr.io/umati/sample-server:develop
    container_name: sampleserver
