---
name: build

on:
  push:
    branches: [main, develop]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: [main, develop]
  merge_group:

permissions: read-all

jobs:
  build-linux:
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm]
        build_type: [Debug, Release]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          path: umatiGateway

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: |
          cd umatiGateway
          dotnet restore

      - name: Install deb packaging tool
        run: |
          cd umatiGateway/umatiGateway
          dotnet tool install --global dotnet-deb
          export PATH="$PATH:/home/runner/.dotnet/tools"
          dotnet deb install

      - name: build and package
        run: |
          cd umatiGateway/umatiGateway
          dotnet deb --configuration ${{ matrix.build_type }} --output ../umati-gateway.deb

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: umatiGateway-${{ matrix.os }}-${{ matrix.build_type }}
          path: umatiGateway/umati-gateway.deb

  build-windows:
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        build_type: [Debug, Release]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Restore Dependencies
        run: dotnet restore umatiGateway.sln

      - name: Build Application
        run: dotnet build umatiGateway.sln --configuration ${{ matrix.build_type }}

      - name: Run Tests
        run: dotnet test umatiGateway.sln --configuration ${{ matrix.build_type }}

      - name: Publish Application
        run: dotnet publish umatiGateway.sln --self-contained true --configuration ${{ matrix.build_type }} --output ./publish

      - name: Upload Published Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: umatiGateway-${{ matrix.os }}-${{ matrix.build_type }}
          path: ./publish

  docker:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-24.04
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          path: umatiGateway

      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.5.0
        #if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          driver-opts: network=host

      - name: Build and Push container image to ${{ env.REGISTRY }}
        uses: docker/build-push-action@v6.18.0
        #if: github.event_name != 'pull_request'
        with:
          context: ./umatiGateway
          file: "./umatiGateway/umatiGateway/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false

      - name: Build and Push container image to local registry
        uses: docker/build-push-action@v6.18.0
        if: github.event_name == 'pull_request'
        with:
          context: ./umatiGateway
          file: "./umatiGateway/umatiGateway/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: localhost:5000/umati/umatigateway:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false

      - name: Run integration test mqtt
        if: github.event_name == 'pull_request'
        run: |
          #!/bin/bash
          cd ./umatiGateway/tests/integration/mqtt_test || exit
          docker compose up -d
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ./waitForContainer.sh
          python -m unittest discover test_mqtt_sampleserver

  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    needs: [build-linux, build-windows, docker]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          workflow_conclusion: success
          repo: ${{ github.repository }}
          commit: ${{github.event.pull_request.head.sha}}
          if_no_artifact_found: fail
          skip_unpack: true
      - name: Checksum
        run: |
          #!/bin/bash
          sha256sum ./*.zip > SHA256-checksums
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./*.zip
            SHA256-checksums
