
on:
  workflow_dispatch:  # Manuelle Ausführung ermöglichen

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Run Prettier Check
        run: npx prettier --check "docs/user/usage.md" --log-level debug
